# -*- coding: utf-8 -*-

from . import sale_order
from . import sale_order_line
from . import sale_subchapter
from . import sale_capitulo
from . import sale_unidad_obra
from . import product_template
from . import res_company
from . import project_task_material
from . import project
from . import project_task
from . import stock_picking
from . import account_analytic_line
from . import project_production
from . import project_certification
from . import project_certification_line
from . import project_certification_capitulo_line
from . import account_move
from . import account_move_line
from . import purchase_order
from . import stock_move
from . import stock_return_picking
from . import product_product
from . import product_unidad_obra
from . import hr_employee
from . import hr_employee_public
from . import hr_employee_extra_hour
from . import sale_order_type
from . import cost_classification
from . import sale_line_unidad_cost
from . import task_project_production_cost
from . import task_account_analytic_line_cost
from . import project_sale_order_cost
from . import project_account_analytic_line_cost
from . import sale_measurement
from . import planning_slot
