# -*- coding: utf-8 -*-
{
    'name': "Indaws Inbuilt",
    'summary': """Indaws Inbuilt""",
    "website": "www.indaws.es",
    "author": "INDAWS",
    'category': 'sales',
    'version': '16.0.0.0.1',
    'license': 'OPL-1',
    'depends': [
        'base',
        'sale_project',
        'uom',
        'product',
        'account',
        'purchase',
        'web',
        'sale_margin',
        'sale_timesheet',
        'analytic',
        'project',
        'purchase_stock',
        'hr_timesheet',
        'stock',
        'mail',
        # 'web_tree_dynamic_colored_field' # modulo de la OCA no disponible en la V16
        'hr',
        'sale_stock',
        'project_purchase',
        'sale_order_type',
        'hr_hourly_cost',
        'planning',
        'project_forecast',
        'sale_order_qty_change_no_recompute'
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/sale_capitulo_wizard.xml',
        'views/sale_views.xml',
        'views/capitulos_views.xml',
        'views/sale_order_line.xml',
        'views/product_template_views.xml',
        'views/sale_unidad_obra_views.xml',
        'report/persupueto_detallado_template.xml',
        'report/sale_order_report.xml',
        'views/res_company_inherit.xml',
        'views/stock_picking.xml',
        'views/project_views.xml',
        'wizard/task_make_invoice_advance.xml',
        'views/project_task_views.xml',
        'views/project_task_material_views.xml',
        'wizard/views_creat_obra.xml',
        'views/task_summary_view.xml',
        'wizard/project_production_task_wizard.xml',
        'views/project_production_views.xml',
        'views/account_move_view.xml',
        'views/project_certification_views.xml',
        'report/qweb/bevia_certification_template.xml',
        'report/qweb/report_bevia_certification.xml',
        'views/email_certification_template.xml',
        'views/purchase_order_views.xml',
        # 'views/stock_move_views.xml',   not used
        'views/account_analytic_line_view.xml',
        'views/product_unidades_obra_views.xml',
        'views/hr_employee_extra_hour_view.xml',
        'views/hr_employee_view.xml',
        'wizard/create_po_from_material_wizard.xml',
        'report/project_work_summary_report.xml',
        'report/project_work_summary_report_by_task.xml',
        'report/task_work_summary_report.xml',
        'views/sale_order_type_view.xml',
        'views/cost_classification_view.xml',
        'report/presupuesto_mediciones_report.xml',
        'report/presupuesto_certificaciones_mediciones.xml',
        'views/planning_slot_view.xml',
        'report/report_certifications_without_measurements.xml'

    ],
    'installable': True,
    'auto_install': True,
    'application': False,
}
